# Generated by Django 3.1.3 on 2020-11-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pone',
            new_name='phone',
        ),
    ]
